### ISSUE TITLE
Panic on attempt to initialise config

### ISSUE THREAD

**Issue by obalunenko** [goreleaser/chglog#119]
Hi @caarlos0 

I get Panic on attempt to initialise config in the root of my repository.

```
chglog config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100c6b730]

goroutine 1 [running]:
github.com/goreleaser/chglog/pkg/commands.setupConfigCmd.func2(0x140001a4600?, {0x1011f07e0?, 0x0?, 0x0?})
	github.com/goreleaser/chglog@v0.4.0/pkg/commands/config.go:27 +0x30
github.com/spf13/cobra.(*Command).execute(0x140001a4600, {0x1011f07e0, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:896 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x140001a4000)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	github.com/goreleaser/chglog@v0.4.0/cmd/chglog/main.go:51 +0x27c
```

## Environent
- go version go1.20 darwin/arm64
- chglog version: v0.4.0
- git version 2.37.1 (Apple Git-137.1)
- os version: macOS 13.2 

## Notes
The same issue with `version` command

```
chglog version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104c34a10]

goroutine 1 [running]:
github.com/goreleaser/chglog/pkg/commands.setupVersionCmd.func1(0x1400021e300?, {0x1051b87e0?, 0x0?, 0x0?})
	github.com/goreleaser/chglog@v0.4.0/pkg/commands/version.go:16 +0x30
github.com/spf13/cobra.(*Command).execute(0x1400021e300, {0x1051b87e0, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:896 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x1400021e000)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	github.com/goreleaser/chglog@v0.4.0/cmd/chglog/main.go:51 +0x27c
```

**Comment by caarlos0** [comment]
thanks for reporting, should be fixed on v0.4.1 (releasing it now)

**Comment by masonkatz** [comment]
v0.4.1 fixed init but the other commands still panic

#123 fixes the other commands

**Comment by caarlos0** [comment]
weird, I seem to remember testing it... looks like I didn't

sorry about that, and thanks for pinging here again
